version: '3'

services:
  web:
    build: .
    command: gunicorn microSaaS.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    entrypoint: ["./wait-for-it.sh", "db:5432", "--", "./start-web.sh"]

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: "microSaaSdatabse"
      POSTGRES_USER: "microSaaSuser"
      POSTGRES_PASSWORD: "microSaaSuser"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
